id: I5EA832A2
legacy_id: P000710
ocr_import_info:
  bdrc_scan_id: W1KG3552
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T04:27:28'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:09:15.647710+00:00'
last_modified: 2022-08-31 23:09:20.304118
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3552
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3552
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསང་སྔགས་རྡོ་རྗེ་ཐེག་པའི་ཚུལ་ལས་སྣང་བ་ལྷར་བསྒྲུབ་དང། སྲོག་སྡོམ་གཟེར་བཞིའི་དམིགས་པའི་གནད།
  author: རྫ་དཔལ་སྤྲུལ་ཨོ་རྒྱན་འཇིགས་མེད་ཆོས་ཀྱི་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9350673156808346
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG3620:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3620
      total_pages: 58
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3620.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9350673156808346
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
