id: I5EA832A2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T04:27:53+00:00'
last_modified: '2022-06-07T12:43:15.411759+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3552
  title: གསང་སྔགས་རྡོ་རྗེ་ཐེག་པའི་ཚུལ་ལས་སྣང་བ་ལྷར་བསྒྲུབ་དང། སྲོག་སྡོམ་གཟེར་བཞིའི་དམིགས་པའི་གནད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9522':
      image_group_id: I1KG3620
      title: ''
      total_pages: 58
      order: 1
      base_file: 9522.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
