id: P000710
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-16 16:38:19.263590
source_metadata:
  id: bdr:W1KG3552
  title: གསང་སྔགས་རྡོ་རྗེ་ཐེག་པའི་ཚུལ་ལས་སྣང་བ་ལྷར་བསྒྲུབ་དང། སྲོག་སྡོམ་གཟེར་བཞིའི་དམིགས་པའི་གནད
  author: ''
  volumes:
    a5fdd5a50b14474c8e0e1e8acc6a171c:
      image_group_id: I1KG3620
      title: ''
      volume_number: 1
      total_pages: 58
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
