id: opecha:P000710
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3552
  title: གསང་སྔགས་རྡོ་རྗེ་ཐེག་པའི་ཚུལ་ལས་སྣང་བ་ལྷར་བསྒྲུབ་དང། སྲོག་སྡོམ་གཟེར་བཞིའི་དམིགས་པའི་གནད
  volume: ''
  author: ''
